server:
  port: 8080
spring:
  application:
    name: redis-server
  redis:
    database: 0
    #host: 9.134.64.243
    #port: 7001
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 9.134.64.243:7001
        - 9.134.64.243:7002
        - 9.134.64.243:7003
        - 9.134.64.243:7004
        - 9.134.64.243:7005
        - 9.134.64.243:7006
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 30s # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0